language:
    - python

python:
    - "3.3"

before_install:
    - sudo apt-get update
    - "wget https://launchpad.net/ubuntu/+source/cmake/2.8.8-2ubuntu1/+build/3441442/+files/cmake_2.8.8-2ubuntu1_amd64.deb"
    - "wget https://launchpad.net/ubuntu/+archive/primary/+files/cmake-data_2.8.8-2ubuntu1_all.deb"
    - "sudo apt-get remove cmake-data cmake"

install:
    - sudo apt-get install doxygen
    - "sudo dpkg --install cmake-data_2.8.8-2ubuntu1_all.deb cmake_2.8.8-2ubuntu1_amd64.deb"

before_script:
    - cmake --version
    - export SUGAR_ROOT=`pwd`

script:
    - cd ./examples
    - chmod +x ./test.py
    - ./test.py
    - make -C 08-doxygen/_builds/make-default/ public-doc # test installed doxygen
