language:
    - python

python:
    - "3.3"

before_install:
    - sudo apt-get update

install:
    - sudo apt-get install doxygen

before_script:
    - export SUGAR_ROOT=`pwd`

script:
    # test some example without GITENV_ROOT
    - cd examples
    - cd 05-groups
    - mkdir _builds
    - cd _builds
    - cmake ..
    - make
    - ./sources/module_a/main/module_a_bin
    - cd ../../..

    # emulate GITENV_ROOT for test.py
    - cd ..
    - export GITENV_ROOT=`pwd`
    - git clone --depth=1 --branch=master https://github.com/ruslo/configs
    - cd sugar
    # -- emulation end

    - cd ./examples
    - chmod +x ./test.py
    # exclude real GITENV_ROOT (see gitenv testing)
    - ./test.py --exclude ./03-gtest ./04-boost-detect ./09-rapidjson
    - make -C 08-doxygen/_builds/make-default/ public-doc # test installed doxygen
