language:
    - objective-c

before_install:
    - brew update
    - brew install cmake
    - brew install python3
    - brew install doxygen
    - brew install boost # boost.config (06-ios)

before_script:
    - cmake --version
    - export SUGAR_ROOT=`pwd`

script:
    - cd ./examples
    - python3 ./test.py --sim --libcxx
