language:
    - objective-c

before_install:
    - brew update

install:
    - brew install python3
    - brew install doxygen
    - brew install cmake
    # install patched cmake version
    - wget https://github.com/ruslo/CMake/archive/ios.universal.2.tar.gz
    - tar xf ios.universal.2.tar.gz
    - cmake -HCMake-ios.universal.2 -B_builds/cmake -DCMAKE_USE_SYSTEM_CURL=YES -DCMAKE_BUILD_TYPE=Release
    - cmake --build _builds/cmake
    - sudo cmake --build _builds/cmake --target install
    # --end

    # install ios simulator for 03/04 examples
    #     * https://github.com/travis-ci-tester/travis-test-ios-sim
    - wget https://github.com/phonegap/ios-sim/archive/1.8.2.tar.gz
    - tar -xvf 1.8.2.tar.gz
    - cd ios-sim-1.8.2/
    - xcodebuild -target ios-sim
    - export PATH=`pwd`/build/Release:${PATH}
    - cd ..
    # -- end

before_script:
    - which cmake
    - cmake --version
    - export SUGAR_ROOT=`pwd`

script:
    - cd ./examples
    - python3 ./test.py --sim --libcxx
